
numeric_table_columns = [
    {"key": "cnt", "label": "Count", "format": "float", "description": "Total number of observations in the dataset"},
    {"key": "missing_cnt", "label": "Missing Count", "format": "float", "description": "Number of missing values"},
    {"key": "missing_pct", "label": "Missing Percent", "format": "float", "description": "Percentage of missing values"},
    {"key": "outlier_cnt", "label": "Outlier Count", "format": "float", "description": "Number of outlier values"},
    {"key": "zeros_cnt", "label": "Zeros Count", "format": "float", "description": "Number of zero values"},
    {"key": "negative_cnt", "label": "Negative Count", "format": "float", "description": "Number of negative values"},
    {"key": "unique_cnt", "label": "Unique Count", "format": "float", "description": "Number of unique values"},
    {"key": "mean", "label": "Mean", "format": "float", "description": "Average value"},
    {"key": "median", "label": "Median", "format": "float", "description": "Middle value"},
    {"key": "mode", "label": "Mode", "format": "float", "description": "Most frequent value"},
    {"key": "std_dev", "label": "Standard Deviation", "format": "float", "description": "Measure of the amount of variation or dispersion"},
    {"key": "var", "label": "Variance", "format": "float", "description": "Measure of the amount of variation or dispersion"},
    {"key": "min", "label": "Minimum", "format": "float", "description": "Minimum value"},
    {"key": "p10", "label": "10th Percentile", "format": "float", "description": "10th percentile value"},
    {"key": "p25", "label": "25th Percentile", "format": "float", "description": "25th percentile value"},
    {"key": "p75", "label": "75th Percentile", "format": "float", "description": "75th percentile value"},
    {"key": "p90", "label": "90th Percentile", "format": "float", "description": "90th percentile value"},
    {"key": "p95", "label": "95th Percentile", "format": "float", "description": "95th percentile value"},
    {"key": "iqr", "label": "Inter-Quartile Range", "format": "float", "description": "Range between the 25th and 75th percentiles"},
    {"key": "skew", "label": "Skewness", "format": "float", "description": "Measure of the asymmetry of the distribution"},
    {"key": "kurtosis", "label": "Kurtosis", "format": "float", "description": "Measure of the tailedness of the distribution"},
    {"key": "mad", "label": "Mean Absolute Deviation", "format": "float", "description": "Measure of the average absolute deviation from the mean"},
    {"key": "sem", "label": "Standard Error of the Mean", "format": "float", "description": "Measure of the precision of the sample mean"},
    {"key": "cv", "label": "Coefficient of Variation", "format": "float", "description": "Relative measure of the variability of the dataset"},
    {"key": "mean_ci_95_low", "label": "Mean 95% Confidence Interval Lower Bound", "format": "float", "description": "Lower bound of the 95%% confidence interval for the mean"},
    {"key": "mean_ci_95_high", "label": "Mean 95% Confidence Interval Upper Bound", "format": "float", "description": "Upper bound of the 95%% confidence interval for the mean"},
]

categoric_table_columns = [
    {"key": "cnt", "label": "Count", "format": "int", "description": "Number of occurrences"},
    {"key": "missing_cnt", "label": "Missing Count", "format": "int", "description": "Number of missing values"},
    {"key": "missing_pct", "label": "Missing Percent", "format": "float", "description": "Percentage of missing values"},
    {"key": "categories", "label": "Categories", "format": "int", "description": "Number of unique categories"},
    {"key": "mode", "label": "Mode", "format": "str", "description": "Most frequent category"},
    {"key": "mode_cnt", "label": "Mode Count", "format": "int", "description": "Number of occurrences of the mode"},
    {"key": "mode_pct", "label": "Mode Percent", "format": "float", "description": "Percentage of occurrences of the mode"},
    {"key": "second_mode", "label": "Second Mode", "format": "str", "description": "Second most frequent category"},
    {"key": "second_mode_cnt", "label": "Second Mode Count", "format": "int", "description": "Number of occurrences of the second mode"},
    {"key": "second_mode_pct", "label": "Second Mode Percent", "format": "float", "description": "Percentage of occurrences of the second mode"},
    {"key": "least_frequent", "label": "Least Frequent Category", "format": "str", "description": "Least frequent category"},
    {"key": "least_frequent_cnt", "label": "Least Frequent Count", "format": "int", "description": "Number of occurrences of the least frequent category"},
    {"key": "least_frequent_pct", "label": "Least Frequent Percent", "format": "float", "description": "Percentage of occurrences of the least frequent category"},
    {"key": "entropy", "label": "Entropy", "format": "float", "description": "Measure of the uncertainty or randomness in the data"},
    {"key": "normalized_entropy", "label": "Normalized Entropy", "format": "float", "description": "Entropy normalized by the maximum possible entropy"},
    {"key": "concentration_ratio", "label": "Concentration Ratio", "format": "float", "description": "Measure of the concentration of values in the data"},
]
